COMPONENT=SendingBuffer_AppC

#CFLAGS += -I$(TOSDIR)/lib/printf
#PFLAGS += -DPRINTF_BUFFER_SIZE=1000
#CFLAGS += -I$(shell pwd)/..
#TINYOS_ROOT_DIR?=../../../../
#include $(TINYOS_ROOT_DIR)/Makefile.include

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp
include $(MAKERULES)
